### ISSUE TITLE
android 4.4（api 19）上崩溃错误，java.lang.NoClassDefFoundError: android/util/Size

### ISSUE THREAD

**Issue by ghost** [yangpeixing/YImagePicker#117]
java.lang.NoClassDefFoundError: android/util/Size
        at java.lang.Class.getDeclaredFields(Native Method)
        at java.lang.Class.getDeclaredFields(Class.java:610)
        at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:258)
        at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1067)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:1035)
        at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:248)
        at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1067)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1574)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
        at android.os.Parcel.writeSerializable(Parcel.java:1311)
        at android.os.Parcel.writeValue(Parcel.java:1264)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
        at android.os.Bundle.writeToParcel(Bundle.java:1692)
        at android.os.Parcel.writeBundle(Parcel.java:636)
        at android.content.Intent.writeToParcel(Intent.java:7013)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2076)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1536)
        at android.app.Activity.startActivityFromFragment(Activity.java:3957)
        at android.app.Fragment.startActivityForResult(Fragment.java:1079)
        at android.app.Fragment.startActivityForResult(Fragment.java:1063)
        at com.ypx.imagepicker.helper.launcher.PRouter.startActivityForResult(PRouter.java:37)
        at com.ypx.imagepicker.helper.launcher.PLauncher.startActivityForResult(PLauncher.java:95)
        at com.ypx.imagepicker.activity.multi.MultiImagePickerActivity.intent(MultiImagePickerActivity.java:60)
        at com.ypx.imagepicker.builder.MultiPickerBuilder.pick(MultiPickerBuilder.java:348)

     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.util.Size" on path: DexPathList[[zip file "/data/app/com.androidarch-1.apk", zip file "/data/data/com.androidarch/code_cache/secondary-dexes/com.androidarch-1.apk.classes2.zip", zip file "/data/data/com.androidarch/code_cache/secondary-dexes/com.androidarch-1.apk.classes3.zip", zip file "/data/data/com.androidarch/code_cache/secondary-dexes/com.androidarch-1.apk.classes4.zip"],nativeLibraryDirectories=[/data/app-lib/com.androidarch-1, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at java.lang.Class.getDeclaredFields(Native Method) 
        at java.lang.Class.getDeclaredFields(Class.java:610) 
        at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:258) 
        at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1067) 
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:1035) 
        at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:248) 
        at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1067) 
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1574) 
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517) 
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481) 
        at android.os.Parcel.writeSerializable(Parcel.java:1311) 
        at android.os.Parcel.writeValue(Parcel.java:1264) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:618) 
        at android.os.Bundle.writeToParcel(Bundle.java:1692) 
        at android.os.Parcel.writeBundle(Parcel.java:636) 
        at android.content.Intent.writeToParcel(Intent.java:7013) 
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2076) 
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1536) 
        at android.app.Activity.startActivityFromFragment(Activity.java:3957) 
        at android.app.Fragment.startActivityForResult(Fragment.java:1079) 
        at android.app.Fragment.startActivityForResult(Fragment.java:1063) 
        at com.ypx.imagepicker.helper.launcher.PRouter.startActivityForResult(PRouter.java:37) 
        at com.ypx.imagepicker.helper.launcher.PLauncher.startActivityForResult(PLauncher.java:95) 
        at com.ypx.imagepicker.activity.multi.MultiImagePickerActivity.intent(MultiImagePickerActivity.java:60) 
        at com.ypx.imagepicker.builder.MultiPickerBuilder.pick(MultiPickerBuilder.java:348) 

android studio 4.1，minSdk 19，maxSdk 30，高版本没问题，就是4.4 报错

**Comment by ghost** [comment]
你提供的demo也有这个问题，点最底下那个加号选择图片时崩溃。

**Comment by MyFisherTiger** [comment]
看报错提示，一般是你的方法数超过了限制吧，开启multidex应该就可以了？
