### ISSUE TITLE
java.lang.VerifyError: Rejecting class com.ypx.imagepicker.activity.crop.MultiImageCropFragment that attempts to sub-type erroneous class com.ypx.imagepicker.activity.PBaseLoaderFragment (declaration of 'com.ypx.imagepicker.activity.crop.MultiImageCropFragment' appears in base.apk!classes24.dex)

### ISSUE THREAD

**Issue by zhangchao1122** [yangpeixing/YImagePicker#146]
把imagepicker模块集成进项目，调用ImagePicker.withCrop(RedBookPresenter())，一直报错，有人遇到过吗？ java.lang.VerifyError: Rejecting class com.ypx.imagepicker.activity.crop.MultiImageCropFragment that attempts to sub-type erroneous class com.ypx.imagepicker.activity.PBaseLoaderFragment (declaration of 'com.ypx.imagepicker.activity.crop.MultiImageCropFragment' appears in base.apk!classes24.dex)
                                                                                                            at com.ypx.imagepicker.builder.CropPickerBuilder.pickWithFragment(CropPickerBuilder.java:234)
                                                                                                            at com.ypx.imagepicker.activity.crop.MultiImageCropActivity.setFragment(MultiImageCropActivity.java:94)
                                                                                                            at com.ypx.imagepicker.activity.crop.MultiImageCropActivity.onCreate(MultiImageCropActivity.java:85)
                                                                                                            at android.app.Activity.performCreate(Activity.java:7224)
                                                                                                            at android.app.Activity.performCreate(Activity.java:7213)
                                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
                                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3114)
                                                                                                            at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                                            at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
                                                                                                            at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
                                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
                                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                            at android.os.Looper.loop(Looper.java:201)
                                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6831)
                                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
                                                                                                    Caused by: java.lang.VerifyError: Verifier rejected class com.ypx.imagepicker.activity.PBaseLoaderFragment: void com.ypx.imagepicker.activity.PBaseLoaderFragment.loadMediaSets() failed to verify: void com.ypx.imagepicker.activity.PBaseLoaderFragment.loadMediaSets(): [0x19] register v3 has type Reference: com.ypx.imagepicker.activity.PBaseLoaderFragment but expected Reference: android.app.Activity
                                                                                                     void com.ypx.imagepicker.activity.PBaseLoaderFragment.takePhoto() failed to verify: void com.ypx.imagepicker.activity.PBaseLoaderFragment.takePhoto(): [0x1F] register v4 has type Reference: com.ypx.imagepicker.activity.PBaseLoaderFragment but expected Reference: android.app.Activity
                                                                                                     void com.ypx.imagepicker.activity.PBaseLoaderFragment.takeVideo() failed to verify: void com.ypx.imagepicker.activity.PBaseLoaderFragment.takeVideo(): [0x1F] register v8 has type Reference: com.ypx.imagepicker.activity.PBaseLoaderFragment but expected Reference: android.app.Activity (declaration of 'com.ypx.imagepicker.activity.PBaseLoaderFragment' appears in base.apk!classes24.dex)

**Comment by bsxy000** [comment]
现在自从iOS支持Live实况图之后，android厂商的相机也支持拍摄动态照片了，还得支持Live图的选择，你现在用的什么图片选择器呢？
