### ISSUE TITLE
长图预览崩溃

### ISSUE THREAD

**Issue by ooyueoo** [yangpeixing/YImagePicker#29]
长图预览奔溃
![image](https://user-images.githubusercontent.com/17006513/69021545-160ee800-09f3-11ea-9f87-911c3ba5f17a.png)

**Comment by yangpeixing** [comment]
@ooyueoo  感谢反馈，报的错是 too large？可以方便贴出崩溃日志吗？

**Comment by ooyueoo** [comment]
2019-12-02 11:46:08.606 32044-32052/? E/zygote64: Failed writing handshake bytes (-1 of 14): Broken pipe
2019-12-02 11:46:18.574 32044-32044/com.ypx.imagepickerdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ypx.imagepickerdemo, PID: 32044
    java.lang.RuntimeException: Canvas: trying to draw too large(108794880bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.widget.ImageView.onDraw(ImageView.java:1371)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.onDraw(CropImageView.java:693)
        at android.view.View.draw(View.java:19145)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.draw(CropImageView.java:738)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.draw(View.java:19148)
        at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.draw(View.java:19148)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:652)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:658)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:766)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3045)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2840)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2393)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1426)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6873)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:792)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by ooyueoo** [comment]
2019-12-02 11:46:08.606 32044-32052/? E/zygote64: Failed writing handshake bytes (-1 of 14): Broken pipe
2019-12-02 11:46:18.574 32044-32044/com.ypx.imagepickerdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ypx.imagepickerdemo, PID: 32044
    java.lang.RuntimeException: Canvas: trying to draw too large(108794880bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.widget.ImageView.onDraw(ImageView.java:1371)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.onDraw(CropImageView.java:693)
        at android.view.View.draw(View.java:19145)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.draw(CropImageView.java:738)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.draw(View.java:19148)
        at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.draw(View.java:19148)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:652)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:658)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:766)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3045)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2840)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2393)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1426)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6873)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:792)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by yangpeixing** [comment]
@ooyueoo  已经修复，请等待3.0正式版本发布（这周内）

**Comment by yangpeixing** [comment]
@ooyueoo 已经push了，你可以先看下

**Comment by yangpeixing** [comment]
3.0已修复

**Comment by JustinChiang123** [comment]
全景图 调用.crop() 直接GG

**Comment by JustinChiang123** [comment]
java.lang.RuntimeException: Canvas: trying to draw too large(123654700bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1436)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.onDraw(CropImageView.java:712)
        at android.view.View.draw(View.java:21975)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.draw(CropImageView.java:757)
        at android.view.View.updateDisplayListIfDirty(View.java:20852)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21978)
        at android.view.View.updateDisplayListIfDirty(View.java:20852)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.updateDisplayListIfDirty(View.java:20843)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.updateDisplayListIfDirty(View.java:20843)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21978)
        at com.android.internal.policy.DecorView.draw(DecorView.java:808)
        at android.view.View.updateDisplayListIfDirty(View.java:20852)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3767)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3495)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2779)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
