### ISSUE TITLE
设置STYLE_GAP属性裁切出错

### ISSUE THREAD

**Issue by tmxd09887** [yangpeixing/YImagePicker#54]
.cropStyle(CropConfig.STYLE_GAP) 设置这个属性，出现崩溃

E/WindowManager: android.view.WindowLeaked: Activity com.ypx.imagepicker.activity.singlecrop.SingleCropActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{3ee562b V.E..... R......D 0,0-684,206} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at android.app.Dialog.show(Dialog.java:298)
        at android.app.ProgressDialog.show(ProgressDialog.java:116)
        at android.app.ProgressDialog.show(ProgressDialog.java:99)
        at android.app.ProgressDialog.show(ProgressDialog.java:94)
        at dev.widget.WeChatPresenter.showProgressDialog(WeChatPresenter.java:143)
        at com.ypx.imagepicker.activity.singlecrop.SingleCropActivity.generateCropFile(SingleCropActivity.java:180)
        at com.ypx.imagepicker.activity.singlecrop.SingleCropActivity$1.onClick(SingleCropActivity.java:142)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.j

**Comment by yangpeixing** [comment]
@tmxd09887 您好，出现这个崩溃信息代表有dialog没有关闭就结束了activity，我这边复查了一下，已经在每次剪裁结束时dismiss了加载框，不知道您这边为什么会出现这个问题，可否加我微信calor0616联调一下？
