### ISSUE TITLE
全景图调用裁剪直接奔溃

### ISSUE THREAD

**Issue by JustinChiang123** [yangpeixing/YImagePicker#59]
日志：
Google Pixel 3 Android 10, API 29

java.lang.RuntimeException: Canvas: trying to draw too large(123654700bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1436)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.onDraw(CropImageView.java:712)
        at android.view.View.draw(View.java:21975)
        at com.ypx.imagepicker.widget.cropimage.CropImageView.draw(CropImageView.java:757)
        at android.view.View.updateDisplayListIfDirty(View.java:20852)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21978)
        at android.view.View.updateDisplayListIfDirty(View.java:20852)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.updateDisplayListIfDirty(View.java:20843)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.updateDisplayListIfDirty(View.java:20843)
        at android.view.View.draw(View.java:21707)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21978)
        at com.android.internal.policy.DecorView.draw(DecorView.java:808)
        at android.view.View.updateDisplayListIfDirty(View.java:20852)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3767)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3495)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2779)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

代码：
ImagePicker
                //指定presenter
                .withMulti(new WeChatPresenter())
                //设置列数
                .setColumnCount(4)
                //设置要加载的文件类型，可指定单一类型
                .mimeTypes(MimeType.ofImage())
                //显示拍照
                .showCamera(true)
                //当单选或者视频单选时，点击item直接回调，无需点击完成按钮
                .setSinglePickWithAutoComplete(true)
                //设置上一次操作的图片列表，下次选择时默认恢复上一次选择的状态
                .setLastImageList(null)
                //设置需要屏蔽掉的图片列表，下次选择时已屏蔽的文件不可选择
                .setShieldList(null)
                //裁剪比例
                .setCropRatio(1, 1)
                //剪裁完成的图片是否保存在DCIM目录下
                //true：存储在DCIM下 false：存储在 data/包名/files/imagePicker/ 目录下
                .cropSaveInDCIM(false)
                //设置剪裁框间距，单位px
                .cropRectMinMargin(50)
                //设置剪裁模式，留白或充满  CropConfig.STYLE_GAP 或 CropConfig.STYLE_FILL
                .cropStyle(CropConfig.STYLE_FILL)
                //设置留白模式下生成的图片背景色，支持透明背景
                .cropGapBackgroundColor(Color.TRANSPARENT)
               .crop(XXXXActivity.this, (OnImagePickCompleteListener) mImageList -> {。。。  });

**Comment by yangpeixing** [comment]
非常感谢您提出问题，长图剪裁崩溃的问题已经解决，但未发布版本，需要耐心等待3.1版本发布，长图预览崩溃的问题，还请提供崩溃的手机机型和安卓系统，以及框架使用的版本

**Comment by JustinChiang123** [comment]
Google Pixel 3 Android 10, API 29

    implementation 'com.ypx.yimagepicker:androidx:3.0.1'

**Comment by yangpeixing** [comment]
可否加我微信，把那个长图发给我，我这边测试一下，因为我代码中默认会对长图做一次尺寸压缩，还请加我微信calor0616🙏
