### ISSUE TITLE
demo中选择过滤视频预览会崩溃

### ISSUE THREAD

**Issue by charmeleon2** [yangpeixing/YImagePicker#60]
大图预览时，过滤掉视频预览
只要选择包含视频，预览就会崩溃。看了下是一个数组越界的问题

**Comment by charmeleon2** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ypx.imagepickerdemo/com.ypx.imagepicker.activity.preview.MultiImagePreviewActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.ypx.imagepicker.activity.preview.MultiImagePreviewActivity.initViewPager(MultiImagePreviewActivity.java:242)
        at com.ypx.imagepicker.activity.preview.MultiImagePreviewActivity.loadMediaPreviewList(MultiImagePreviewActivity.java:178)
        at com.ypx.imagepicker.activity.preview.MultiImagePreviewActivity.onCreate(MultiImagePreviewActivity.java:131)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)

**Comment by yangpeixing** [comment]
@charmeleon2 感谢您的反馈!我这边demo复现不出来,可否加我微信calor0616,我们联调一下

**Comment by charmeleon2** [comment]
@yangpeixing 你有尝试过只选一个视频然后大图预览吗

**Comment by yangpeixing** [comment]
@charmeleon2

**Comment by yangpeixing** [comment]
@charmeleon2 感谢反馈,忽视了下面的预览按钮,新版本会修复掉🌹

**Comment by charmeleon2** [comment]
再提一个小建议，关闭预览编辑的时候，预览界面右下角的选择按钮不应该显示

**Comment by yangpeixing** [comment]
@charmeleon2   3.0版本以后没有预览编辑了,预览页面逻辑全部由使用者自定义了

**Comment by yangpeixing** [comment]
3.1版本已修复此问题
