### ISSUE TITLE
support:3.1.1 长图崩溃

### ISSUE THREAD

**Issue by hxzzZ** [yangpeixing/YImagePicker#67]
com.ypx.yimagepicker:support:3.1.1 是最新的代码吗？ Demo可以正常使用，添加依赖，选取长图片就会崩溃。

java.lang.RuntimeException: Canvas: trying to draw too large(205576960bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.widget.ImageView.onDraw(ImageView.java:1370)
        at android.view.View.draw(View.java:19337)
        at android.view.View.updateDisplayListIfDirty(View.java:18266)
        at android.view.View.draw(View.java:19054)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
        at android.view.View.draw(View.java:19340)
        at android.view.View.updateDisplayListIfDirty(View.java:18266)
        at android.view.View.draw(View.java:19054)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4401)

**Comment by yangpeixing** [comment]
@hxzzZ 我刚测试了3.1.1依赖版本,并没有出现长途崩溃,可否加我w calor0616 我们一起看下问题

**Comment by hxzzZ** [comment]
抱歉，这是我的问题。GlideApp设置apply RequestOptions.bitmapTransform()
