### ISSUE TITLE
 java.lang.RuntimeException: Parcelable encountered IOException writing serializable object 

### ISSUE THREAD

**Issue by as1105** [yangpeixing/YImagePicker#70]
你好，我这边采用自定义 模式，发现2部手机都有问题，能看看是啥问题么？
手机型号荣耀V30Pro，magic emui：3.0.1 ， 小米mix2 ，miui：11
操作： takePhotoAndCrop，点击相册，成功拍照，拍照页面点击右上角 进入裁剪页面时报错
` java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:1, request=9048, result=-1, data=null} to activity {com.zzgx.zyly_client/com.zzgx.zyly_client.ui.home.HomeActivity}: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.zzgx.zyly_client.ui.home.UserFragment$3)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5492)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5533)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2401)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8210)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.zzgx.zyly_client.ui.home.UserFragment$3)
        at android.os.Parcel.writeSerializable(Parcel.java:1833)
        at android.os.Parcel.writeValue(Parcel.java:1780)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1588)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:997)
        at android.content.Intent.writeToParcel(Intent.java:10735)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3860)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1887)
        at android.app.Activity.startActivityForResult(Activity.java:6147)
        at android.app.Activity.startActivityFromFragment(Activity.java:6115)
        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:8918)
        at android.app.Fragment.startActivityForResult(Fragment.java:1128)
        at android.app.Fragment.startActivityForResult(Fragment.java:1117)
        at com.ypx.imagepicker.helper.launcher.PRouter.startActivityForResult(PRouter.java:37)
        at com.ypx.imagepicker.helper.launcher.PLauncher.startActivityForResult(PLauncher.java:95)
        at com.ypx.imagepicker.activity.singlecrop.SingleCropActivity.intentCrop(SingleCropActivity.java:82)
        at com.ypx.imagepicker.ImagePicker$1.onImagePickComplete(ImagePicker.java:142)
        at com.ypx.imagepicker.helper.CameraCompat$1.onActivityResult(CameraCompat.java:76)
        at com.ypx.imagepicker.helper.launcher.PRouter.onActivityResult(PRouter.java:61)
        at android.app.Activity.dispatchActivityResult(Activity.java:8439)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5485)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5533) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2401) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8210) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: java.io.NotSerializableException: com.zzgx.zyly_client.ui.home.UserFragment
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
        at android.os.Parcel.writeSerializable(Parcel.java:1828)
        at android.os.Parcel.writeValue(Parcel.java:1780) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1588) 
        at android.os.Bundle.writeToParcel(Bundle.java:1253) 
        at android.os.Parcel.writeBundle(Parcel.java:997) 
        at android.content.Intent.writeToParcel(Intent.java:10735) 
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3860) 
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1887) 
        at android.app.Activity.startActivityForResult(Activity.java:6147) 
        at android.app.Activity.startActivityFromFragment(Activity.java:6115) 
        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:8918) 
        at android.app.Fragment.startActivityForResult(Fragment.java:1128) 
        at android.app.Fragment.startActivityForResult(Fragment.java:1117) 
        at com.ypx.imagepicker.helper.launcher.PRouter.startActivityForResult(PRouter.java:37) 
        at com.ypx.imagepicker.helper.launcher.PLauncher.startActivityForResult(PLauncher.java:95) 
        at com.ypx.imagepicker.activity.singlecrop.SingleCropActivity.intentCrop(SingleCropActivity.java:82) 
        at com.ypx.imagepicker.ImagePicker$1.onImagePickComplete(ImagePicker.java:142) 
        at com.ypx.imagepicker.helper.CameraCompat$1.onActivityResult(CameraCompat.java:76) 
        at com.ypx.imagepicker.helper.launcher.PRouter.onActivityResult(PRouter.java:61) 
        at android.app.Activity.dispatchActivityResult(Activity.java:8439) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5485) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5533) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2401) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8210) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) `

**Comment by yangpeixing** [comment]
@as1105 demo是否出现同样错误？我这边测试demo没有这个问题

**Comment by as1105** [comment]
你好，我运行了demo 没有问题， 我刚测了下，发现同样的 takePhotoAndCrop 放到 activity 则没有问题， 运用在 fragment里面就会出现这个bug，不知道是不是这个原因

**Comment by yangpeixing** [comment]
@as1105  我放入到了fragment中，未发现这个问题，可否加我联系方式把你的调用代码给我看下。微信 calor0616
