### ISSUE TITLE
想问下里面用到的AndroidX版本是1.1.0吗？

### ISSUE THREAD

**Issue by LiuDongCai** [yangpeixing/YImagePicker#71]
想问下里面用到的AndroidX版本是1.1.0吗？
1.1.0会有问题，具体问题可参考https://stackoverflow.com/questions/58209943/how-to-fix-boolean-androidx-fragment-app-fragmentmanagerimpl-isdestroyed-on
如果AndroidX切换成1.0.2版本则不会出现

因为我项目中是遇到过这样的问题，所以切换成1.0.2了，但是引入YImagePicker后又出现了，所以想问是不是这个原因？如果是的话能否麻烦切换下AndroidX版本

**Comment by yangpeixing** [comment]
@LiuDongCai 现阶段我所有框架以及项目的androidx版本都是1.1.0，未出现过你链接里面的问题。

**Comment by LiuDongCai** [comment]
`2020-04-08 17:21:42.886 26563-26563/com.addcn.android.house591 E/CrashReport: java.lang.RuntimeException: Unable to destroy activity {com.addcn.android.house591/com.addcn.android.house591.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManagerImpl.isDestroyed()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManagerImpl.isDestroyed()' on a null object reference
        at androidx.fragment.app.Fragment.performDetach(Fragment.java:2849)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1034)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at com.addcn.android.house591.base.BaseActivity.onDestroy(BaseActivity.java:266)
        at com.addcn.android.house591.ui.MainActivity.onDestroy(MainActivity.java:510)
        at android.app.Activity.performDestroy(Activity.java:7479)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `

我的baseactivity是这样的：
BaseActivity extends AppCompatActivity
然后是在下面出现错误的
 @Override
    protected void onDestroy() {
        super.onDestroy();
}

**Comment by LiuDongCai** [comment]
https://blog.csdn.net/ccc920123/article/details/104356948
招到问题了，是onDetach();，注释掉这个方法就可以，但是具体是为什么我还是不清楚
